// pattern: Functional Core

import type { DigestData } from "./builder";

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/**
 * Renders digest data to an HTML email string with inline styles.
 *
 * @param data - The structured digest data to render
 * @returns A complete HTML email document with inline CSS styles suitable for email clients.
 *          All styles are inline (no `<style>` tags) for compatibility with email clients.
 *          Output includes proper HTML escaping for XSS safety (AC3.3).
 */
export function renderDigestHtml(data: Readonly<DigestData>): string {
  const isoString = new Date().toISOString();
  const now = isoString.split("T")[0]!;

  const topicSections = data.topicGroups
    .map((group) => {
      const articleItems = group.articles
        .map((article) => {
          const title = article.title ?? "Untitled";
          const dateline = article.publishedAt
            ? article.publishedAt.toISOString().split("T")[0]!
            : "";
          const tagsStr =
            article.tags.length > 0 ? article.tags.join(", ") : "";

          return `
        <div style="margin-bottom:16px;padding:12px;border-left:3px solid #2563eb;background:#f8fafc;">
          <h3 style="margin:0 0 4px 0;font-size:16px;">
            <a href="${escapeHtml(article.url)}" style="color:#2563eb;text-decoration:none;">${escapeHtml(title)}</a>
          </h3>
          ${dateline ? `<p style="margin:0 0 8px 0;color:#64748b;font-size:13px;">${escapeHtml(dateline)}</p>` : ""}
          ${article.summary ? `<p style="margin:0 0 8px 0;font-size:14px;line-height:1.5;">${escapeHtml(article.summary)}</p>` : ""}
          ${tagsStr ? `<p style="margin:0;font-size:12px;color:#94a3b8;">Tags: ${escapeHtml(tagsStr)}</p>` : ""}
        </div>`;
        })
        .join("\n");

      return `
      <h2 style="margin:24px 0 12px 0;font-size:20px;color:#1e293b;border-bottom:1px solid #e2e8f0;padding-bottom:8px;">
        ${escapeHtml(group.topicName)}
      </h2>
      ${articleItems}`;
    })
    .join("\n");

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;max-width:640px;margin:0 auto;padding:20px;color:#1e293b;">
  <h1 style="font-size:24px;margin-bottom:4px;">Horizon Scan Digest</h1>
  <p style="color:#64748b;margin-top:0;">${escapeHtml(now)} &middot; ${data.totalArticleCount} article${data.totalArticleCount !== 1 ? "s" : ""}</p>
  ${topicSections}
  <hr style="border:none;border-top:1px solid #e2e8f0;margin-top:32px;">
  <p style="font-size:12px;color:#94a3b8;">Generated by Horizon Scan</p>
</body>
</html>`;
}
